project_name: "carrot_LargeBudget"
environment:
  type: "table"
  file_path: "data/processed/bert-base-uncased/sprout_test/online_cost_scale_1000.parquet"
agent:
  type: "carrot"
  mu: 0.4
log_dir: "outputs/log0919"
T: 530
budget: 100