project_name: "carrot_LargeBudget"
environment:
  type: "table"
  file_path: "data/processed/bert-base-uncased/sprout_test/online_cost_scale_1000.parquet"
agent:
  type: "carrot2"
  mu: 0.7
  rmodel:
    type: "xgbregressor"
    offline : True
    sft_file_path: "data/processed/bert-base-uncased/sprout/offline_cost_scale_1000.parquet"
  cmodel:
    type: "xgbregressor"
    offline : True
    sft_file_path: "data/processed/bert-base-uncased/sprout/offline_cost_scale_1000.parquet"
  embedding_fn: "sample2given_embedding"
log_dir: "outputs/log0919"
T: 5309
budget: 1500