project_name: "xgb_AUPD_routerbench_v=1e-1"
environment:
  type: "table"
  file_path: "data/processed/bert-base-uncased/sprout_small/online_cost_scale_1000.parquet"
agent:
  type: "carrot"
  mu: 0.9
log_dir: "outputs/log0908"
T: 10618
budget: 2000