project_name: "routerbench_0shot_olknn"
environment:
  type: "table"
  file_path: "data/processed/bert-base-uncased/sprout/online_cost_scale_1000.parquet"
agent:
  type: "google"
  lambda : 0.85
  rmodel:
    type: "olknn"
    file_path: "data/processed/bert-base-uncased/sprout/offline_cost_scale_1000.parquet"
    k : 100
    offline : True
  cmodel:
    type: "olknn"
    file_path: "data/processed/bert-base-uncased/sprout/offline_cost_scale_1000.parquet"
    k : 100
    offline : True
  embedding_fn: "sample2given_embedding"
log_dir: "outputs/log0919"
T: 5309
budget: 436