project_name: "routerbench_0shot"
environment:
  type: "table"
  file_path: "data/processed/bert-base-uncased/routerbench_0shot/online_cost_scale_1000_cleaned.parquet"
agent:
  type: "google"
  lambda : 0.06
  # rmodel:
  #   type: "god"
  #   file_path: "data/processed/bert-base-uncased/routerbench_0shot_gpt4_llama270b/online_cost_scale_1000.parquet"
  rmodel:
    type: "kmeans"
    file_path: "data/processed/bert-base-uncased/routerbench_0shot/online_cost_scale_1000_cleaned.parquet"
    k : 20
  # rmodel:
  #   type: "xgb"
  #   offline : False
  #   sft_file_path: "data/processed/bert-base-uncased/routerbench_0shot_gpt4_llama270b/online_cost_scale_1000.parquet"
  # cmodel:
  #   type: "god"
  #   file_path: "data/processed/bert-base-uncased/routerbench_0shot_gpt4_llama270b/online_cost_scale_1000.parquet"
  # cmodel:
  #   type: "mf"
  #   sft_file_path: None
  cmodel:
    type: "kmeans"
    file_path: "data/processed/bert-base-uncased/routerbench_0shot/online_cost_scale_1000_cleaned.parquet"
    k : 1
  embedding_fn: "sample2given_embedding"
log_dir: "outputs/log0916"
T: 20000
budget: 8000