project_name: "hfmodel_AUPD_sprout"
environment:
  type: "table"
  file_path: "data/processed/bert-base-uncased/sprout_test/online_cost_scale_1000.parquet"
agent:
  type: "AUPD"
  v_scale : 0.1
  allow_null : False
  eta : 20
  rmodel:
    type: "hf_model"
    key: "reward"
    model_name_or_path: "./models/carrot-preformance"
  cmodel:
    type: "hf_model"
    key: "length"
    model_name_or_path: "./models/carrot-cost"
    cost_table: {
            'aws-claude-3-5-sonnet-v1': [3, 15], 'aws-titan-text-premier-v1': [0.5, 1.5],
            'openai-gpt-4o': [2.5, 10], 'openai-gpt-4o-mini': [0.15, 0.6],
            'wxai-granite-3-2b-instruct-8k-max-tokens': [0.1, 0.1],
            'wxai-granite-3-8b-instruct-8k-max-tokens': [0.2, 0.2],
            'wxai-llama-3-1-70b-instruct': [0.9, 0.9], 'wxai-llama-3-1-8b-instruct': [0.2, 0.2],
            'wxai-llama-3-2-1b-instruct': [0.06, 0.06], 'wxai-llama-3-2-3b-instruct': [0.06, 0.06],
            'wxai-llama-3-3-70b-instruct': [0.9, 0.9], 'wxai-mixtral-8x7b-instruct-v01': [0.6, 0.6],
            'wxai-llama-3-405b-instruct': [3.5, 3.5]
        }
    input_counter_path_or_name: "./models/Llama-3.2-3B"
  embedding_fn: "sample2prompt"
log_dir: "outputs/log_AUPD_batch"
T: 5309
budget: 400