project_name: "mf_AUPD_server_routerbench"
environment:
  type: "server"
  data_path: "data/processed/qa-version/routerbench_0shot/all.parquet"
  reward_fn: "str_cmp"
  embedder:
    type: "SentenceTransformerEmbedder"
    model_path: "models/all-mpnet-base-v2"
  model_info: 
    "deepseek-r1:32b":
      api_key: "EMPTY"
      base_url: "http://127.0.0.1:11434/v1"
      description: "A math model based on Qwen2.5-7B"
      cost_per_token: 0.01
    "llama3.1:8b":
      api_key: "EMPTY"
      base_url: "http://127.0.0.1:11434/v1"
      description: "A cost effective model"
      cost_per_token: 0.01
    # deepseek-v3:
    #   api_key: "sk-068Hb5cMckD0AAEjA31a4d372b394792B0C62b3d2523Ac0e"
    #   base_url: "https://api.apiyi.com/v1"
    #   cost_per_token: 1
    #   description: "ababaabab"
    # gemini-1.5-flash:
    #   api_key: "sk-068Hb5cMckD0AAEjA31a4d372b394792B0C62b3d2523Ac0e"
    #   base_url: "https://api.apiyi.com/v1"
    #   cost_per_token: 0.9
    #   description: "description"
agent:
  type: "AUPD"
  v_scale : 0.1
  allow_null : False
  rmodel:
    type: "mf"
    sft_file_path: None
  cmodel:
    type: "mf"
    sft_file_path: None
  embedding_fn: "sample2prompt"
log_dir: "outputs/logs"
T: 25000
budget: 150000