project_name: "xgb_AUPD_routerbench"
environment:
  type: "table"
  file_path: "data/processed/all-mpnet-base-v2/routerbench_0shot/online.parquet"
agent:
  type: "AUPD"
  rmodel:
    type: "xgb"
    sft_file_path: "data/processed/all-mpnet-base-v2/routerbench_0shot/offline.parquet"
  cmodel:
    type: "xgb"
    sft_file_path: "data/processed/all-mpnet-base-v2/routerbench_0shot/offline.parquet"
  embedding_fn: "sample2given_embedding"
log_dir: "outputs/logs"
T: 29196
budget: 10