project_name: "routerbench_0shot"
environment:
  type: "table"
  file_path: "/home/zulk2024/ICLR2026/data/processed/bert-base-uncased/routerbench_0shot/online_cost_scale_1000_cleaned.parquet"
agent:
  type: "ratio"
  rmodel:
    type: "olknn"
    file_path: "data/processed/bert-base-uncased/routerbench_0shot/offline_cost_scale_1000.parquet"
    k : 100
    offline : False
  cmodel:
    type: "olknn"
    file_path: "data/processed/bert-base-uncased/routerbench_0shot/offline_cost_scale_1000.parquet"
    k : 100
    offline : False
  embedding_fn: "sample2given_embedding"
log_dir: "outputs/log0916"
T: 20000
budget: 20000