project_name: "AUPD_exp_routerbench"
environment:
  type: "table"
  file_path: "data/processed/bert-base-uncased/routerbench_0shot/online_cost_scale_1000_cleaned.parquet"
agent:
  type: "AUPD_exp"
  v_scale : 1
  eta: 100
  allow_null : False
  rmodel:
    type: "olknn"
    file_path: "data/processed/bert-base-uncased/routerbench_0shot/offline_cost_scale_1000.parquet"
    k : 50
    offline : False
  cmodel:
    type: "olknn"
    file_path: "data/processed/bert-base-uncased/routerbench_0shot/offline_cost_scale_1000.parquet"
    k : 50
    offline : False
  embedding_fn: "sample2prompt"
log_dir: "outputs/log0919"
T: 2000
budget: 200