project_name: "AUPD_exp_sp"
environment:
  type: "table"
  file_path: "data/processed/bert-base-uncased/sprout_test/online_cost_scale_1000.parquet"
agent:
  type: "AUPD_exp"
  v_scale : 1
  eta: 20
  allow_null : False
  rmodel:
    type: "olknn"
    file_path: "data/processed/bert-base-uncased/sprout_test/offline_cost_scale_1000.parquet"
    k : 100
    offline : False
  cmodel:
    type: "olknn"
    file_path: "data/processed/bert-base-uncased/sprout_test/offline_cost_scale_1000.parquet"
    k : 100
    offline : False
  embedding_fn: "sample2prompt"
log_dir: "outputs/log0919"
T: 5309
budget: 900