project_name: "conservation"
environment:
  type: "table"
  file_path: "data/processed/bert-base-uncased/sprout_test/online_cost_scale_1000.parquet"
agent:
  type: "cons"
  rmodel:
    type: "olknn"
    file_path: "data/processed/bert-base-uncased/sprout_test/offline_cost_scale_1000.parquet"
    k : 100
    offline : False
  cmodel:
    type: "olknn"
    file_path: "data/processed/bert-base-uncased/sprout_test/offline_cost_scale_1000.parquet"
    k : 100
    offline : False
  embedding_fn: "sample2given_embedding"
log_dir: "outputs/log0919"
T: 5309
budget: 900